CREATE TABLE "facilities_assets" (
	"id" text PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"category" text NOT NULL,
	"type" text,
	"brand" text,
	"model" text,
	"serial_number" text,
	"purchase_date" timestamp with time zone,
	"start_using_date" timestamp with time zone,
	"location_id" text,
	"location_name" text,
	"responsible_user_id" text,
	"responsible_user_name" text,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"maintenance_priority" text,
	"last_maintenance_date" timestamp with time zone,
	"next_maintenance_date" timestamp with time zone,
	"image_url" text,
	"qr_code" text,
	"note" text,
	"archived_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "facilities_assets_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "facilities_handover_logs" (
	"id" text PRIMARY KEY NOT NULL,
	"asset_id" text NOT NULL,
	"asset_name" text,
	"receiver_id" text NOT NULL,
	"receiver_name" text,
	"department" text,
	"handover_date" timestamp with time zone NOT NULL,
	"expected_return_date" timestamp with time zone,
	"actual_return_date" timestamp with time zone,
	"condition_on_handover" text,
	"condition_on_return" text,
	"handed_over_by_id" text,
	"handed_over_by_name" text,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"note" text,
	"attachment_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "facilities_locations" (
	"id" text PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"building" text,
	"floor" text,
	"capacity" integer,
	"manager_id" text,
	"manager_name" text,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "facilities_locations_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "facilities_maintenance_logs" (
	"id" text PRIMARY KEY NOT NULL,
	"asset_id" text NOT NULL,
	"asset_name" text,
	"maintenance_type" text NOT NULL,
	"scheduled_date" timestamp with time zone NOT NULL,
	"completed_date" timestamp with time zone,
	"responsible_user_id" text,
	"responsible_user_name" text,
	"status" text DEFAULT 'SCHEDULED' NOT NULL,
	"checklist" jsonb,
	"result" text,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "facilities_repair_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"asset_id" text,
	"asset_name" text,
	"location_id" text,
	"location_name" text,
	"description" text NOT NULL,
	"priority" text DEFAULT 'MEDIUM' NOT NULL,
	"status" text DEFAULT 'NEW' NOT NULL,
	"requested_by_id" text NOT NULL,
	"requested_by_name" text,
	"assigned_to_id" text,
	"assigned_to_name" text,
	"due_date" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"resolution_note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
