import { StrategicOkr, OkrGroup, KeyResult, OkrTask, AuditLog, OkrStatus, Priority } from "@/src/types/okr";

export const mockOkrGroups: OkrGroup[] = [
  { id: "G01", code: "TS", name: "Tuyển sinh & tăng trưởng", color: "blue", icon: "Users", totalOkrs: 2, onTrack: 1, delayed: 0, atRisk: 1, avgProgress: 65 },
  { id: "G02", code: "CL", name: "Chất lượng giáo dục", color: "emerald", icon: "BookOpen", totalOkrs: 2, onTrack: 2, delayed: 0, atRisk: 0, avgProgress: 80 },
  { id: "G03", code: "GV", name: "Đội ngũ giáo viên", color: "indigo", icon: "GraduationCap", totalOkrs: 1, onTrack: 0, delayed: 1, atRisk: 0, avgProgress: 45 },
  { id: "G04", code: "TC", name: "Tài chính vận hành", color: "amber", icon: "DollarSign", totalOkrs: 1, onTrack: 0, delayed: 0, atRisk: 1, avgProgress: 30 },
  { id: "G05", code: "PH", name: "Chăm sóc phụ huynh", color: "rose", icon: "HeartHandshake", totalOkrs: 1, onTrack: 1, delayed: 0, atRisk: 0, avgProgress: 75 },
  { id: "G06", code: "IT", name: "Chuyển đổi số", color: "cyan", icon: "MonitorSmartphone", totalOkrs: 1, onTrack: 1, delayed: 0, atRisk: 0, avgProgress: 90 },
  { id: "G07", code: "CS", name: "Cơ sở vật chất & an toàn", color: "slate", icon: "Building", totalOkrs: 1, onTrack: 0, delayed: 1, atRisk: 0, avgProgress: 50 },
  { id: "G08", code: "PR", name: "Thương hiệu & truyền thông", color: "violet", icon: "Megaphone", totalOkrs: 1, onTrack: 1, delayed: 0, atRisk: 0, avgProgress: 60 }
];

export const mockOkrs: StrategicOkr[] = [
  {
    id: "OKR-2025-01",
    code: "TS-01",
    title: "Tăng quy mô tuyển sinh năm học 2025-2026 thêm 20%",
    description: "Tập trung tuyển sinh các khối đầu cấp (Lớp 1, 6, 10). Tối ưu tỷ lệ chuyển đổi từ Lead sang Nhập học.",
    schoolYear: "2025-2026",
    categoryId: "G01",
    ownerName: "Nguyễn Văn Tuyển",
    ownerRole: "Trưởng phòng Tuyển sinh",
    department: "Phòng Tuyển sinh",
    collaborators: ["Phòng Marketing", "Phòng Tài chính"],
    startDate: "2025-01-01",
    endDate: "2025-08-30",
    priority: "Critical",
    status: "InProgress",
    progressPercent: 45,
    targetValue: 800,
    currentValue: 360,
    unit: "Học sinh",
    riskLevel: "Medium",
    lastUpdatedAt: "2025-06-20T10:00:00Z",
    nextReviewDate: "2025-06-30",
    notes: "Tỷ lệ chuyển đổi đang bị chậm ở khâu chốt phí.",
    keyResults: [
      { id: "KR-01", okrId: "OKR-2025-01", title: "Đạt 800 lead tuyển sinh chất lượng cao", metricName: "Leads", targetValue: 800, currentValue: 450, unit: "Lead", progressPercent: 56, ownerName: "Trưởng phòng Marketing", deadline: "2025-07-30", status: "OnTrack", confidenceLevel: "High", updateFrequency: "Weekly", evidenceNote: "Chiến dịch Facebook Ads đang chạy tốt.", lastUpdatedAt: "2025-06-20T10:00:00Z" },
      { id: "KR-02", okrId: "OKR-2025-01", title: "Đạt 350 HS tham gia test đầu vào", metricName: "Test", targetValue: 350, currentValue: 120, unit: "HS", progressPercent: 34, ownerName: "Trưởng phòng Tuyển sinh", deadline: "2025-08-15", status: "Delayed", confidenceLevel: "Medium", updateFrequency: "Weekly", evidenceNote: "Tỷ lệ rớt lịch test cao do trùng lịch thi trường khác.", lastUpdatedAt: "2025-06-20T10:00:00Z" }
    ],
    actionItems: [
      { id: "TSK-01", okrId: "OKR-2025-01", title: "Khởi chạy chiến dịch Early Bird đợt 2", ownerName: "Nguyễn Văn Tuyển", deadline: "2025-06-25", status: "InProgress", priority: "High" }
    ],
    auditLogs: []
  },
  {
    id: "OKR-2025-02",
    code: "CL-01",
    title: "Nâng cao chất lượng giảng dạy và kiểm soát giáo án",
    description: "Đảm bảo 100% giáo án được duyệt trước khi lên lớp và tăng tỷ lệ giờ dạy giỏi.",
    schoolYear: "2025-2026",
    categoryId: "G02",
    ownerName: "Lê Thị Thu",
    ownerRole: "Phó Hiệu trưởng Học vụ",
    department: "Ban Giám hiệu",
    collaborators: ["Các Tổ chuyên môn"],
    startDate: "2025-02-01",
    endDate: "2025-12-30",
    priority: "High",
    status: "OnTrack",
    progressPercent: 80,
    targetValue: 100,
    currentValue: 80,
    unit: "%",
    riskLevel: "Low",
    lastUpdatedAt: "2025-06-21T09:00:00Z",
    nextReviewDate: "2025-07-01",
    notes: "",
    keyResults: [],
    actionItems: [],
    auditLogs: []
  },
  {
    id: "OKR-2025-03",
    code: "TC-01",
    title: "Kiểm soát tỷ lệ thu học phí đúng hạn đạt 95%",
    description: "Giảm tỷ lệ nợ đọng học phí, tăng cường dòng tiền hoạt động.",
    schoolYear: "2025-2026",
    categoryId: "G04",
    ownerName: "Phạm Văn Tài",
    ownerRole: "Kế toán trưởng",
    department: "Phòng Tài chính",
    collaborators: ["Phòng Giáo vụ", "Phòng Tuyển sinh"],
    startDate: "2025-01-01",
    endDate: "2025-12-31",
    priority: "Critical",
    status: "AtRisk",
    progressPercent: 30,
    targetValue: 95,
    currentValue: 60,
    unit: "%",
    riskLevel: "High",
    lastUpdatedAt: "2025-06-22T14:00:00Z",
    nextReviewDate: "2025-06-25",
    notes: "Kỳ vọng dòng tiền tháng 6 bị hụt do 40% phụ huynh xin gia hạn.",
    keyResults: [
      { id: "KR-03", okrId: "OKR-2025-03", title: "Thu 100% học phí đợt 1 trước 15/07", metricName: "Thu phí đợt 1", targetValue: 100, currentValue: 60, unit: "%", progressPercent: 60, ownerName: "Phạm Văn Tài", deadline: "2025-07-15", status: "AtRisk", confidenceLevel: "Low", updateFrequency: "Weekly", evidenceNote: "Tiến độ thu chậm do hệ thống gửi thông báo bị trễ 1 tuần.", lastUpdatedAt: "2025-06-22T14:00:00Z" }
    ],
    actionItems: [
      { id: "TSK-02", okrId: "OKR-2025-03", title: "Gửi SMS nhắc phí lần 2 cho nhóm quá hạn", ownerName: "Phạm Văn Tài", deadline: "2025-06-24", status: "Pending", priority: "Critical" }
    ],
    auditLogs: []
  },
  {
    id: "OKR-2025-04",
    code: "GV-01",
    title: "Chuẩn hóa đội ngũ giáo viên và hồ sơ chuyên môn",
    description: "Tuyển dụng đủ giáo viên trước thềm năm học mới và hoàn thiện 100% hồ sơ.",
    schoolYear: "2025-2026",
    categoryId: "G03",
    ownerName: "Trần Nhân Sự",
    ownerRole: "Trưởng phòng HCNS",
    department: "Phòng Hành chính Nhân sự",
    collaborators: ["Ban Giám hiệu"],
    startDate: "2025-03-01",
    endDate: "2025-07-15",
    priority: "High",
    status: "Delayed",
    progressPercent: 45,
    targetValue: 100,
    currentValue: 45,
    unit: "%",
    riskLevel: "Medium",
    lastUpdatedAt: "2025-06-20T08:00:00Z",
    nextReviewDate: "2025-06-25",
    notes: "Đang thiếu 3 giáo viên Tiếng Anh bản ngữ.",
    keyResults: [],
    actionItems: [],
    auditLogs: []
  },
  {
    id: "OKR-2025-05",
    code: "IT-01",
    title: "Số hóa 100% quy trình báo cáo, phê duyệt và văn bản",
    description: "Triển khai MIS Smart Portal giai đoạn 2 cho tất cả các phòng ban.",
    schoolYear: "2025-2026",
    categoryId: "G06",
    ownerName: "Bùi Văn Tech",
    ownerRole: "Trưởng phòng IT",
    department: "Phòng IT",
    collaborators: ["Tất cả phòng ban"],
    startDate: "2025-01-01",
    endDate: "2025-10-30",
    priority: "Medium",
    status: "OnTrack",
    progressPercent: 90,
    targetValue: 100,
    currentValue: 90,
    unit: "%",
    riskLevel: "Low",
    lastUpdatedAt: "2025-06-24T08:00:00Z",
    nextReviewDate: "2025-07-01",
    notes: "Đã golive module Tuyển sinh và Hội đồng.",
    keyResults: [],
    actionItems: [],
    auditLogs: []
  }
];
